# -*- coding: utf-8 -*-
"""
Terjemahan Indonesia untuk 311 Intermediate Work Activity (IWA) O*NET yang
dipakai 464 profesi kita.

Kenapa lapisan ini yang diterjemahkan: O*NET menyusun pekerjaan sebagai
GWA (41) -> IWA (332) -> DWA (2.087) -> Task Statement (18.796). IWA adalah
lapisan terkecil yang masih dipakai ulang lintas profesi, jadi 311 kalimat di
sini memberi milestone berbahasa Indonesia untuk seluruh knowledge base —
sementara menerjemahkan task statement berarti 18.796 kalimat yang tidak
dipakai ulang sama sekali.

Nada terjemahan: frasa capaian yang dibaca siswa ("Membaca dokumen kerja untuk
memahami proses"), bukan terjemahan harfiah kalimat perintah O*NET.
"""

IWA_ID = {
    # --- Getting Information -------------------------------------------------
    "4.A.1.a.1.a": "Menelaah detail produksi karya seni",
    "4.A.1.a.1.b": "Membaca dokumen kerja untuk memahami proses",
    "4.A.1.a.1.c": "Menyelidiki perkara hukum atau kriminal",
    "4.A.1.a.1.d": "Mengumpulkan informasi dari sumber fisik maupun digital",
    "4.A.1.a.1.e": "Menelusuri dokumen hukum atau catatan publik",
    "4.A.1.a.1.f": "Mengumpulkan data kegiatan operasional atau pengembangan",
    "4.A.1.a.1.g": "Mencari informasi tentang barang atau jasa",
    "4.A.1.a.1.h": "Meneliti isu ilmu kebumian",
    "4.A.1.a.1.i": "Meneliti perilaku, proses, atau kinerja organisasi",
    "4.A.1.a.1.j": "Menelaah dampak lingkungan dari kegiatan industri atau pembangunan",
    "4.A.1.a.1.k": "Mengumpulkan bahan untuk berita",
    "4.A.1.a.1.l": "Menghimpun informasi pasien atau klien",
    "4.A.1.a.1.n": "Menggali kebutuhan dan pendapat konsumen",
    "4.A.1.a.1.p": "Meneliti fenomena biologi atau ekologi",
    "4.A.1.a.1.q": "Mengurus dokumen atau izin resmi",
    "4.A.1.a.1.r": "Meneliti isu sejarah atau sosial",
    "4.A.1.a.1.s": "Meneliti isu kesehatan",
    "4.A.1.a.1.t": "Meneliti rancangan atau penerapan teknologi",
    "4.A.1.a.1.u": "Menyelidiki insiden atau kecelakaan",
    "4.A.1.a.1.v": "Menyelidiki masalah organisasi atau operasional",
    "4.A.1.a.1.w": "Mewawancarai orang untuk menggali informasi",

    # --- Monitoring Processes ------------------------------------------------
    "4.A.1.a.2.a": "Memantau jalannya peralatan",
    "4.A.1.a.2.b": "Memantau operasional agar kinerjanya tetap memadai",
    "4.A.1.a.2.c": "Memantau data atau aktivitas keuangan",
    "4.A.1.a.2.e": "Memantau kondisi kesehatan manusia atau hewan",
    "4.A.1.a.2.f": "Memantau perilaku atau kinerja individu",
    "4.A.1.a.2.g": "Memantau keselamatan dan keamanan area kerja",
    "4.A.1.a.2.h": "Memantau tren dan perkembangan di luar organisasi",
    "4.A.1.a.2.i": "Memantau kondisi lingkungan",
    "4.A.1.a.2.j": "Memantau jalannya sistem komputer atau teknologi informasi",
    "4.A.1.a.2.k": "Memantau kepatuhan operasional terhadap regulasi atau standar",

    # --- Identifying Objects, Actions, Events --------------------------------
    "4.A.1.b.1.a": "Menandai material atau objek untuk identifikasi",
    "4.A.1.b.1.b": "Mengenali peluang bisnis atau organisasi",

    # --- Inspecting ----------------------------------------------------------
    "4.A.1.b.2.a": "Melakukan tes diagnostik untuk menilai kesehatan pasien",
    "4.A.1.b.2.b": "Menilai teknologi atau proses ramah lingkungan",
    "4.A.1.b.2.c": "Menguji karakteristik material atau produk",
    "4.A.1.b.2.d": "Memeriksa kendaraan",
    "4.A.1.b.2.e": "Memeriksa fasilitas atau peralatan",
    "4.A.1.b.2.f": "Memeriksa hasil kerja atau produk jadi",
    "4.A.1.b.2.g": "Memeriksa sistem atau peralatan produksi dan industri",
    "4.A.1.b.2.h": "Menguji kinerja sistem komputer atau sistem informasi",
    "4.A.1.b.2.i": "Memeriksa manusia atau hewan untuk menilai kondisi fisiknya",
    "4.A.1.b.2.j": "Memeriksa karakteristik atau kondisi material dan produk",
    "4.A.1.b.2.k": "Menguji lokasi atau material terhadap bahaya lingkungan",
    "4.A.1.b.2.l": "Menguji kinerja peralatan atau sistem",

    # --- Estimating ----------------------------------------------------------
    "4.A.1.b.3.a": "Mengukur karakteristik fisik material, produk, atau peralatan",
    "4.A.1.b.3.b": "Memperkirakan biaya pengembangan atau operasional proyek",
    "4.A.1.b.3.c": "Menghitung data keuangan",
    "4.A.1.b.3.d": "Menilai karakteristik lahan atau properti",
    "4.A.1.b.3.e": "Melakukan pengukuran fisik pada pasien atau klien",

    # --- Judging Qualities ---------------------------------------------------
    "4.A.2.a.1.a": "Menilai kebutuhan hidup, kerja, atau sosial individu dan komunitas",
    "4.A.2.a.1.b": "Mengevaluasi program, praktik, atau proses",
    "4.A.2.a.1.c": "Menilai kemampuan, kebutuhan, dan capaian peserta didik",
    "4.A.2.a.1.d": "Mengevaluasi kemampuan atau kinerja personel",
    "4.A.2.a.1.e": "Mengevaluasi masukan dan keluaran produksi",
    "4.A.2.a.1.f": "Mengevaluasi kondisi pasien dan pilihan penanganannya",
    "4.A.2.a.1.g": "Menilai kegunaan dan kinerja produk atau teknologi",
    "4.A.2.a.1.h": "Menelaah karya ilmiah",
    "4.A.2.a.1.i": "Menilai kondisi aset keuangan, properti, atau sumber daya lain",
    "4.A.2.a.1.j": "Menilai kelayakan proyek",

    # --- Processing Information ----------------------------------------------
    "4.A.2.a.2.a": "Menilai kualitas dan keakuratan data",
    "4.A.2.a.2.b": "Menyortir material atau produk",
    "4.A.2.a.2.c": "Menghimpun catatan, dokumentasi, dan data",
    "4.A.2.a.2.d": "Merekonsiliasi data keuangan",
    "4.A.2.a.2.e": "Memverifikasi data pribadi",

    # --- Evaluating Compliance -----------------------------------------------
    "4.A.2.a.3.a": "Memeriksa keakuratan dan kepatuhan material atau dokumen",
    "4.A.2.a.3.b": "Menilai kepatuhan terhadap standar dan regulasi lingkungan",
    "4.A.2.a.3.c": "Memeriksa aktivitas, operasi, atau sistem keuangan",
    "4.A.2.a.3.d": "Menjalankan prosedur keselamatan layanan kesehatan",

    # --- Analyzing Data ------------------------------------------------------
    "4.A.2.a.4.a": "Menganalisis data lingkungan atau geospasial",
    "4.A.2.a.4.b": "Menganalisis kondisi pasar atau industri",
    "4.A.2.a.4.c": "Menganalisis risiko bisnis atau keuangan",
    "4.A.2.a.4.d": "Menganalisis data ilmiah dengan prinsip matematika",
    "4.A.2.a.4.e": "Mengevaluasi rancangan, spesifikasi, dan data teknis",
    "4.A.2.a.4.f": "Menganalisis data kesehatan atau medis",
    "4.A.2.a.4.g": "Menganalisis data untuk memperbaiki operasional",
    "4.A.2.a.4.i": "Menilai karakteristik dan dampak regulasi atau kebijakan",
    "4.A.2.a.4.j": "Menganalisis zat biologi, zat kimia, dan datanya",
    "4.A.2.a.4.k": "Menganalisis data bisnis atau keuangan",
    "4.A.2.a.4.l": "Menganalisis kinerja sistem atau peralatan",

    # --- Making Decisions ----------------------------------------------------
    "4.A.2.b.1.a": "Menentukan nilai atau harga barang dan jasa",
    "4.A.2.b.1.b": "Mendiagnosis masalah sistem atau peralatan",
    "4.A.2.b.1.c": "Memberi otorisasi kegiatan atau transaksi bisnis",
    "4.A.2.b.1.d": "Menentukan metode atau prosedur kerja",
    "4.A.2.b.1.f": "Mendiagnosis kondisi atau gangguan kesehatan",
    "4.A.2.b.1.g": "Menyunting naskah atau dokumen",
    "4.A.2.b.1.h": "Menentukan kebutuhan sumber daya proyek atau operasional",
    "4.A.2.b.1.i": "Menerapkan prosedur atau proses kerja",
    "4.A.2.b.1.j": "Memilih material atau peralatan untuk proyek dan operasional",
    "4.A.2.b.1.k": "Mengolah rekaman audio atau video",

    # --- Thinking Creatively -------------------------------------------------
    "4.A.2.b.2.a": "Menyusun rencana perawatan pasien atau klien",
    "4.A.2.b.2.b": "Merancang sistem atau aplikasi komputer",
    "4.A.2.b.2.c": "Menyusun rencana bisnis atau pemasaran",
    "4.A.2.b.2.d": "Menyusun resep atau menu",
    "4.A.2.b.2.e": "Menyusun standar, kebijakan, dan prosedur keselamatan",
    "4.A.2.b.2.f": "Merancang basis data",
    "4.A.2.b.2.g": "Menyusun rencana pengelolaan sumber daya alam",
    "4.A.2.b.2.h": "Menyusun rencana keuangan atau bisnis",
    "4.A.2.b.2.i": "Mengembangkan metode atau program asesmen kesehatan",
    "4.A.2.b.2.j": "Membuat materi pemasaran atau promosi",
    "4.A.2.b.2.k": "Merancang material atau perangkat",
    "4.A.2.b.2.l": "Menyusun program, rencana, dan prosedur pembelajaran",
    "4.A.2.b.2.m": "Mengembangkan cara mengatasi masalah lingkungan",
    "4.A.2.b.2.n": "Mengembangkan program kesehatan masyarakat",
    "4.A.2.b.2.o": "Membuat desain atau tampilan visual",
    "4.A.2.b.2.p": "Menyusun rencana darurat atau kontingensi",
    "4.A.2.b.2.q": "Mengembangkan kebijakan organisasi yang berkelanjutan",
    "4.A.2.b.2.r": "Membuat konten berita, hiburan, atau karya seni",
    "4.A.2.b.2.s": "Menyusun rencana dan metodologi penelitian",
    "4.A.2.b.2.t": "Menciptakan karya desain atau pertunjukan seni",
    "4.A.2.b.2.u": "Mengembangkan teori atau model ilmiah dan matematis",
    "4.A.2.b.2.v": "Merumuskan tujuan dan sasaran organisasi atau program",

    # --- Updating Knowledge / Objectives / Scheduling ------------------------
    "4.A.2.b.3.a": "Memperbarui pengetahuan di bidang keahliannya",
    "4.A.2.b.4.a": "Menyusun kebijakan, sistem, dan proses organisasi",
    "4.A.2.b.5.a": "Menyusun jadwal layanan atau fasilitas",
    "4.A.2.b.5.b": "Menjadwalkan kegiatan operasional",
    "4.A.2.b.5.c": "Mengatur jadwal janji temu",
    "4.A.2.b.6.a": "Merencanakan acara atau program",
    "4.A.2.b.6.b": "Merencanakan aktivitas kerja",

    # --- General Physical Activities -----------------------------------------
    "4.A.3.a.1.a": "Membuat campuran atau larutan",
    "4.A.3.a.1.b": "Melindungi orang dan properti dari ancaman seperti kebakaran atau banjir",
    "4.A.3.a.1.c": "Membersihkan alat, peralatan, fasilitas, dan area kerja",
    "4.A.3.a.1.d": "Memasang struktur atau penutup pelindung di area kerja",
    "4.A.3.a.1.e": "Membuang limbah atau puing",
    "4.A.3.a.1.f": "Memuat produk, material, atau peralatan untuk diangkut",
    "4.A.3.a.1.g": "Melakukan pekerjaan konstruksi atau penggalian umum",
    "4.A.3.a.1.h": "Membersihkan benda kerja atau produk jadi",
    "4.A.3.a.1.i": "Membersihkan peralatan atau fasilitas medis",
    "4.A.3.a.1.j": "Memindahkan material, peralatan, atau perbekalan",
    "4.A.3.a.1.k": "Menjaga keselamatan dan keamanan",
    "4.A.3.a.1.l": "Mengawal atau mendampingi orang",
    "4.A.3.a.1.m": "Mengantar pasien atau klien",
    "4.A.3.a.1.n": "Memanjat peralatan atau struktur bangunan",
    "4.A.3.a.1.p": "Melakukan aktivitas atletik untuk kebugaran, kompetisi, atau seni",
    "4.A.3.a.1.q": "Melakukan kegiatan pertanian",

    # --- Handling and Moving Objects -----------------------------------------
    "4.A.3.a.2.a": "Membangun struktur bangunan",
    "4.A.3.a.2.aa": "Membuat perangkat atau komponen",
    "4.A.3.a.2.ab": "Membuat objek atau ornamen dekoratif",
    "4.A.3.a.2.ac": "Mengolah karkas hewan",
    "4.A.3.a.2.ad": "Mengebor lubang pada tanah atau material",
    "4.A.3.a.2.ae": "Menata atau merapikan rambut",
    "4.A.3.a.2.af": "Menyiapkan ruang kelas, fasilitas, dan materi belajar",
    "4.A.3.a.2.ag": "Mengaplikasikan lapisan atau cairan pelindung",
    "4.A.3.a.2.ah": "Menyambungkan komponen atau saluran ke peralatan",
    "4.A.3.a.2.ai": "Menyambung bagian dengan teknik solder, las, atau brazing",
    "4.A.3.a.2.aj": "Merakit produk atau alat bantu kerja",
    "4.A.3.a.2.ak": "Menata stok perbekalan atau produk",
    "4.A.3.a.2.al": "Mengambil sampel lingkungan atau biologis",
    "4.A.3.a.2.am": "Mengisi celah atau menambal ketidaksempurnaan",
    "4.A.3.a.2.an": "Mengeluarkan benda kerja dari mesin produksi",
    "4.A.3.a.2.ao": "Memosisikan material atau komponen untuk dirakit",
    "4.A.3.a.2.ap": "Mengemas barang",
    "4.A.3.a.2.aq": "Memasang instalasi perpipaan atau sanitasi",
    "4.A.3.a.2.as": "Mengerjakan finishing dekoratif",
    "4.A.3.a.2.at": "Menyiapkan dan memasang peralatan",
    "4.A.3.a.2.au": "Menyiapkan spesimen atau material untuk diuji",
    "4.A.3.a.2.b": "Mengambil sampel produk atau material",
    "4.A.3.a.2.c": "Menyiapkan makanan atau minuman",
    "4.A.3.a.2.d": "Merakit peralatan atau komponen",
    "4.A.3.a.2.e": "Menjahit pakaian atau bahan",
    "4.A.3.a.2.f": "Menempatkan benda kerja atau material pada mesin",
    "4.A.3.a.2.g": "Membentuk material menjadi produk",
    "4.A.3.a.2.h": "Menata display atau dekorasi",
    "4.A.3.a.2.i": "Menyetel peralatan agar kinerjanya optimal",
    "4.A.3.a.2.k": "Menyiapkan peralatan medis dan area kerjanya",
    "4.A.3.a.2.l": "Memotong material",
    "4.A.3.a.2.m": "Menyiapkan material industri untuk diproses",
    "4.A.3.a.2.o": "Menghaluskan permukaan benda atau peralatan",
    "4.A.3.a.2.p": "Memasang peralatan energi atau pemanas",
    "4.A.3.a.2.q": "Membuat alat kesehatan",
    "4.A.3.a.2.s": "Membongkar peralatan",
    "4.A.3.a.2.t": "Memasang peralatan komersial atau produksi",
    "4.A.3.a.2.u": "Mengaplikasikan produk perawatan kulit atau rambut",
    "4.A.3.a.2.v": "Menempatkan alat atau peralatan kerja",
    "4.A.3.a.2.x": "Menyetel peralatan medis agar kinerjanya optimal",
    "4.A.3.a.2.y": "Mengukir atau menggravir benda",

    # --- Controlling Machines ------------------------------------------------
    "4.A.3.a.3.a": "Mengoperasikan peralatan kantor",
    "4.A.3.a.3.b": "Mengoperasikan sistem atau peralatan pompa",
    "4.A.3.a.3.c": "Mengoperasikan alat berat konstruksi atau penggalian",
    "4.A.3.a.3.d": "Mengoperasikan peralatan medis",
    "4.A.3.a.3.e": "Mengoperasikan peralatan audio visual",
    "4.A.3.a.3.f": "Mengoperasikan mesin pengolahan atau produksi industri",
    "4.A.3.a.3.g": "Mengoperasikan peralatan produksi atau distribusi energi",
    "4.A.3.a.3.h": "Mengoperasikan alat angkat dan alat pemindah",
    "4.A.3.a.3.i": "Mengoperasikan peralatan laboratorium atau lapangan",
    "4.A.3.a.3.j": "Mengoperasikan peralatan atau sistem komunikasi",
    "4.A.3.a.3.l": "Mengoperasikan mesin potong atau gerinda",
    "4.A.3.a.4.a": "Mengoperasikan kendaraan atau alat transportasi",

    # --- Working with Computers ----------------------------------------------
    "4.A.3.b.1.a": "Memprogram sistem komputer atau mesin produksi",
    "4.A.3.b.1.b": "Menerapkan pengamanan sistem komputer dan informasi",
    "4.A.3.b.1.c": "Menyiapkan sistem komputer, jaringan, dan sistem informasi",
    "4.A.3.b.1.d": "Menyelesaikan masalah komputer",
    "4.A.3.b.1.e": "Mengoperasikan sistem komputer atau peralatan terkomputerisasi",
    "4.A.3.b.1.f": "Mengolah data digital atau daring",

    # --- Drafting and Specifying ---------------------------------------------
    "4.A.3.b.2.a": "Menyusun spesifikasi teknis produk atau operasional",
    "4.A.3.b.2.b": "Merancang struktur atau fasilitas bangunan",
    "4.A.3.b.2.c": "Merancang sistem atau peralatan industri",
    "4.A.3.b.2.d": "Membuat model sistem, proses, atau produk",
    "4.A.3.b.2.e": "Merancang sistem atau peralatan kelistrikan dan elektronik",
    "4.A.3.b.2.f": "Menyusun prosedur dan standar operasional atau teknis",

    # --- Repairing and Maintaining -------------------------------------------
    "4.A.3.b.4.a": "Merawat fasilitas atau peralatan",
    "4.A.3.b.4.b": "Memperbaiki benda kerja atau produk",
    "4.A.3.b.4.c": "Memperbaiki alat atau peralatan",
    "4.A.3.b.4.d": "Memperbaiki komponen kendaraan",
    "4.A.3.b.4.e": "Menjaga kendaraan tetap layak jalan",
    "4.A.3.b.4.f": "Merawat peralatan atau instrumen medis",
    "4.A.3.b.5.a": "Merawat alat dan peralatan kerja",
    "4.A.3.b.5.b": "Memperbaiki peralatan listrik atau elektronik",
    "4.A.3.b.5.c": "Merawat peralatan elektronik, komputer, dan perangkat teknis lain",

    # --- Documenting / Recording ---------------------------------------------
    "4.A.3.b.6.a": "Menyusun dokumen, laporan, atau anggaran keuangan",
    "4.A.3.b.6.b": "Mencatat informasi perkara hukum",
    "4.A.3.b.6.c": "Mempresentasikan hasil riset atau informasi teknis",
    "4.A.3.b.6.e": "Merekam gambar dengan peralatan foto atau audio visual",
    "4.A.3.b.6.f": "Menyusun dokumen kesehatan atau medis",
    "4.A.3.b.6.g": "Menyusun proposal atau pengajuan hibah",
    "4.A.3.b.6.h": "Memelihara catatan operasional",
    "4.A.3.b.6.i": "Mendokumentasikan rancangan, prosedur, dan kegiatan teknis",
    "4.A.3.b.6.j": "Memelihara catatan penjualan atau keuangan",
    "4.A.3.b.6.k": "Memelihara rekam medis atau catatan kesehatan",
    "4.A.3.b.6.l": "Menyusun materi informasi atau bahan ajar",
    "4.A.3.b.6.m": "Menyiapkan dokumen kontrak, permohonan, atau perizinan",
    "4.A.3.b.6.n": "Menyusun dokumen hukum atau regulasi",
    "4.A.3.b.6.o": "Menyusun laporan kegiatan operasional atau prosedural",
    "4.A.3.b.6.p": "Menulis naskah untuk keperluan seni atau komersial",

    # --- Interpreting for Others ---------------------------------------------
    "4.A.4.a.1.a": "Menjelaskan detail teknis produk atau layanan",
    "4.A.4.a.1.b": "Menjelaskan regulasi, kebijakan, atau prosedur",
    "4.A.4.a.1.c": "Menjadi penerjemah bahasa, budaya, atau keagamaan",
    "4.A.4.a.1.d": "Menjelaskan informasi keuangan",
    "4.A.4.a.1.e": "Menjelaskan informasi medis kepada pasien dan keluarganya",

    # --- Communicating Internally --------------------------------------------
    "4.A.4.a.2.a": "Mengomunikasikan informasi lingkungan dan keberlanjutan",
    "4.A.4.a.2.b": "Membantu ilmuwan atau tenaga ahli dalam proyek dan riset",
    "4.A.4.a.2.c": "Berkoordinasi soal rencana dan kegiatan operasional",
    "4.A.4.a.2.d": "Berdiskusi dengan tenaga kesehatan lain tentang perawatan pasien",
    "4.A.4.a.2.e": "Mengomunikasikan strategi bisnis",
    "4.A.4.a.2.f": "Berkolaborasi mengembangkan program pendidikan",
    "4.A.4.a.2.g": "Melaporkan keadaan darurat atau masalah kepada pihak terkait",
    "4.A.4.a.2.h": "Mengomunikasikan spesifikasi dan detail proyek",
    "4.A.4.a.2.j": "Menggali kebutuhan dan spesifikasi pesanan klien",

    # --- Communicating Externally --------------------------------------------
    "4.A.4.a.3.a": "Menyampaikan keterangan dalam proses hukum",
    "4.A.4.a.3.b": "Memberikan informasi atau bantuan kepada publik",
    "4.A.4.a.3.c": "Memberikan informasi kepada tamu, klien, atau pelanggan",
    "4.A.4.a.4.a": "Membangun relasi dan jejaring profesional",

    # --- Assisting and Caring ------------------------------------------------
    "4.A.4.a.5.a": "Membantu orang lain mengakses layanan atau sumber daya tambahan",
    "4.A.4.a.5.b": "Memberikan terapi",
    "4.A.4.a.5.c": "Memberikan perawatan atau tindakan medis dasar",
    "4.A.4.a.5.d": "Merawat tanaman atau hewan",
    "4.A.4.a.5.e": "Menangani situasi krisis atau darurat",
    "4.A.4.a.5.f": "Memasangkan alat bantu pada pasien atau klien",
    "4.A.4.a.5.g": "Memberikan pertolongan medis darurat",
    "4.A.4.a.5.h": "Membantu orang mengurus berkas",
    "4.A.4.a.5.i": "Mendampingi individu berkebutuhan khusus",
    "4.A.4.a.5.j": "Memberikan bantuan umum kepada pelanggan atau pengguna jalan",
    "4.A.4.a.5.k": "Mengasistensi tenaga kesehatan saat tindakan medis",
    "4.A.4.a.5.l": "Menangani cedera, penyakit, atau gangguan kesehatan",

    # --- Selling and Influencing ---------------------------------------------
    "4.A.4.a.6.a": "Mengadvokasi kebutuhan individu atau komunitas",
    "4.A.4.a.6.b": "Menjual produk atau layanan",
    "4.A.4.a.6.c": "Mempromosikan produk, layanan, atau program",
    "4.A.4.a.7.a": "Menengahi perselisihan",
    "4.A.4.a.7.b": "Menegosiasikan kontrak atau kesepakatan",
    "4.A.4.a.7.c": "Menyelesaikan masalah personel atau operasional",
    "4.A.4.a.8.a": "Menampilkan pertunjukan seni atau hiburan",
    "4.A.4.a.8.c": "Menanggapi keluhan atau pertanyaan pelanggan",

    # --- Coordinating Work ---------------------------------------------------
    "4.A.4.b.1.a": "Berkoordinasi dengan pihak lain untuk menyelesaikan masalah",
    "4.A.4.b.1.b": "Memberi aba-aba untuk mengoordinasikan pekerjaan",
    "4.A.4.b.1.c": "Mengoordinasikan kegiatan dengan klien, instansi, atau organisasi",
    "4.A.4.b.1.d": "Mengoordinasikan kegiatan seni atau hiburan",
    "4.A.4.b.1.e": "Mengoordinasikan kegiatan kelompok atau kemasyarakatan",
    "4.A.4.b.1.f": "Membagi tugas kepada orang lain",
    "4.A.4.b.1.g": "Mengoordinasikan kegiatan kepatuhan regulasi",
    "4.A.4.b.2.a": "Memberi dukungan dan semangat kepada orang lain",

    # --- Training and Teaching -----------------------------------------------
    "4.A.4.b.3.a": "Mengajarkan keterampilan hidup",
    "4.A.4.b.3.b": "Mengajar mata pelajaran akademik atau kejuruan",
    "4.A.4.b.3.c": "Mengajarkan prosedur dan standar keselamatan",
    "4.A.4.b.3.d": "Melatih orang lain tentang prosedur kerja",
    "4.A.4.b.3.e": "Melatih orang lain menggunakan peralatan atau produk",
    "4.A.4.b.3.f": "Memberi edukasi kesehatan kepada orang lain",

    # --- Directing and Managing ----------------------------------------------
    "4.A.4.b.4.a": "Menyupervisi pekerjaan personel",
    "4.A.4.b.4.b": "Terlibat dalam komite organisasi",
    "4.A.4.b.4.e": "Memimpin kegiatan ilmiah atau teknis",
    "4.A.4.b.4.f": "Mengelola kegiatan sumber daya manusia",
    "4.A.4.b.4.g": "Mengelola sistem atau kegiatan pengendalian",
    "4.A.4.b.4.h": "Mengelola anggaran atau keuangan",
    "4.A.4.b.4.i": "Memimpin kegiatan konstruksi atau penggalian",
    "4.A.4.b.4.j": "Mengarahkan operasional dan prosedur organisasi",
    "4.A.4.b.4.k": "Memimpin kegiatan keamanan atau keselamatan",
    "4.A.4.b.4.l": "Memimpin kegiatan hukum",
    "4.A.4.b.5.a": "Membimbing orang lain sebagai coach",

    # --- Consulting and Advising ---------------------------------------------
    "4.A.4.b.6.a": "Memberi nasihat medis kepada pasien atau klien",
    "4.A.4.b.6.b": "Memberi saran tentang produk atau layanan",
    "4.A.4.b.6.c": "Memberi saran tentang keberlanjutan dan praktik ramah lingkungan",
    "4.A.4.b.6.d": "Memberi saran tentang perancangan dan penggunaan teknologi",
    "4.A.4.b.6.e": "Memberi saran tentang urusan bisnis atau operasional",
    "4.A.4.b.6.f": "Memberi saran tentang kesehatan dan kebugaran",
    "4.A.4.b.6.g": "Memberi saran tentang pendidikan atau pilihan karier",
    "4.A.4.b.6.h": "Memberi saran tentang urusan hukum atau regulasi",
    "4.A.4.b.6.i": "Memberi saran tentang kesehatan dan keselamatan kerja",
    "4.A.4.b.6.j": "Memberi konseling tentang masalah pribadi",
    "4.A.4.b.6.k": "Memberi saran tentang urusan keuangan",

    # --- Administrative ------------------------------------------------------
    "4.A.4.c.1.a": "Menjalankan pekerjaan administrasi atau ketatausahaan",
    "4.A.4.c.1.c": "Melaksanakan transaksi keuangan",
    "4.A.4.c.1.d": "Menerbitkan dokumen resmi",
    "4.A.4.c.1.e": "Memproses pengiriman atau surat",
    "4.A.4.c.2.a": "Menjalankan proses rekrutmen dan seleksi",
    "4.A.4.c.2.b": "Menjalankan kegiatan kepegawaian",

    # --- Monitoring and Controlling Resources --------------------------------
    "4.A.4.c.3.a": "Mengisi ulang persediaan material, peralatan, atau produk",
    "4.A.4.c.3.b": "Meminta pemeriksaan atau tindakan medis",
    "4.A.4.c.3.c": "Mendistribusikan material, perbekalan, atau sumber daya",
    "4.A.4.c.3.d": "Menerima pembayaran atau ongkos",
    "4.A.4.c.3.e": "Melakukan pengadaan barang atau jasa",
    "4.A.4.c.3.f": "Meresepkan obat atau alat kesehatan",
    "4.A.4.c.3.g": "Memantau sumber daya atau persediaan",
}

# Nama GWA (41) — dipakai untuk mengelompokkan milestone di UI.
GWA_ID = {
    "4.A.1.a.1": "Mencari informasi",
    "4.A.1.a.2": "Memantau proses, material, atau lingkungan sekitar",
    "4.A.1.b.1": "Mengenali objek, tindakan, dan peristiwa",
    "4.A.1.b.2": "Memeriksa peralatan, struktur, atau material",
    "4.A.1.b.3": "Memperkirakan ukuran dan jumlah",
    "4.A.2.a.1": "Menilai kualitas objek, layanan, atau orang",
    "4.A.2.a.2": "Mengolah informasi",
    "4.A.2.a.3": "Menilai kesesuaian dengan standar",
    "4.A.2.a.4": "Menganalisis data atau informasi",
    "4.A.2.b.1": "Mengambil keputusan dan memecahkan masalah",
    "4.A.2.b.2": "Berpikir kreatif",
    "4.A.2.b.3": "Memperbarui dan menerapkan pengetahuan",
    "4.A.2.b.4": "Menyusun tujuan dan strategi",
    "4.A.2.b.5": "Menjadwalkan pekerjaan dan kegiatan",
    "4.A.2.b.6": "Mengatur, merencanakan, dan memprioritaskan pekerjaan",
    "4.A.3.a.1": "Melakukan aktivitas fisik umum",
    "4.A.3.a.2": "Menangani dan memindahkan benda",
    "4.A.3.a.3": "Mengendalikan mesin dan proses",
    "4.A.3.a.4": "Mengoperasikan kendaraan dan alat bermesin",
    "4.A.3.b.1": "Bekerja dengan komputer",
    "4.A.3.b.2": "Membuat gambar teknik dan spesifikasi perangkat",
    "4.A.3.b.4": "Memperbaiki dan merawat peralatan mekanis",
    "4.A.3.b.5": "Memperbaiki dan merawat peralatan elektronik",
    "4.A.3.b.6": "Mendokumentasikan dan mencatat informasi",
    "4.A.4.a.1": "Menerjemahkan informasi untuk orang lain",
    "4.A.4.a.2": "Berkomunikasi dengan atasan, rekan, dan bawahan",
    "4.A.4.a.3": "Berkomunikasi dengan pihak luar organisasi",
    "4.A.4.a.4": "Membangun dan menjaga hubungan antarpribadi",
    "4.A.4.a.5": "Membantu dan merawat orang lain",
    "4.A.4.a.6": "Menjual atau memengaruhi orang lain",
    "4.A.4.a.7": "Menyelesaikan konflik dan bernegosiasi",
    "4.A.4.a.8": "Tampil atau bekerja langsung dengan publik",
    "4.A.4.b.1": "Mengoordinasikan pekerjaan orang lain",
    "4.A.4.b.2": "Membangun dan mengembangkan tim",
    "4.A.4.b.3": "Melatih dan mengajar orang lain",
    "4.A.4.b.4": "Membimbing, mengarahkan, dan memotivasi bawahan",
    "4.A.4.b.5": "Membina dan mengembangkan orang lain",
    "4.A.4.b.6": "Memberi konsultasi dan saran",
    "4.A.4.c.1": "Menjalankan kegiatan administratif",
    "4.A.4.c.2": "Mengelola kebutuhan personel unit",
    "4.A.4.c.3": "Memantau dan mengendalikan sumber daya",
}
