-- ============================================================================
-- 0018_sub_industries.sql
--
-- Sub-industri per profesi — chip yang muncul di pojok kiri atas tiap kartu
-- profesi di layar Explore.
--
-- Alasannya ditulis sendiri oleh tim desain: "sub-industri lebih membantu user
-- memahami konteks profesi dibanding group industri yang terlalu generik,
-- karena 1 profesi bisa digunakan lebih dari 1 bidang industri." Memang begitu:
-- "Healthcare & Life Sciences" tidak memberi tahu apa pun, sedangkan "Ritel
-- Farmasi" dan "Farmasi Steril" langsung menempatkan profesinya.
--
-- Kosakatanya diambil dari kolom sub_industries di tabel industries — daftar
-- yang tim desain tulis sendiri di sheet Mapping (Industri) — diterjemahkan ke
-- bahasa Indonesia dan dipecah jadi baris, ditambah beberapa yang muncul di
-- mockup tapi belum ada di sheet.
--
-- Pemetaan profesi memakai aturan kata kunci atas nama profesi, dengan rumpun
-- SOC sebagai jaring pengaman. Semuanya bertanda is_verified = false: masuk
-- akal, belum ditinjau manusia.
--
-- Sebagai efek samping, file ini menutup lubang yang tercatat di 0010: 16
-- industri baru yang belum punya satu pun tautan profesi kini terisi, lewat
-- sub-industri yang bernaung di bawahnya.
--
-- Jalankan setelah 0017. Aman diulang.
-- ============================================================================

begin;

create table if not exists public.sub_industries (
  code          text primary key,
  industry_code text not null references public.industries(code) on delete cascade,
  name_id       text not null,
  display_order smallint not null default 99
);

create table if not exists public.career_sub_industries (
  career_id         integer not null references public.careers(id) on delete cascade,
  sub_industry_code text    not null references public.sub_industries(code) on delete cascade,
  is_primary        boolean not null default false,
  display_order     smallint not null default 99,
  source            text    not null default 'aturan_kata_kunci',
  is_verified       boolean not null default false,
  primary key (career_id, sub_industry_code)
);
comment on column public.career_sub_industries.is_primary is
  'Sub-industri yang ditampilkan di chip kartu. Sisanya diringkas jadi penanda "(+N)".';

insert into public.sub_industries (code, industry_code, name_id, display_order) values
  ('TECH_SOFTWARE', 'TECH', 'Software & Aplikasi', 1),
  ('TECH_SAAS', 'TECH', 'SaaS & Produk Digital', 2),
  ('TECH_AI', 'TECH', 'AI & Data Science', 3),
  ('TECH_CYBER', 'TECH', 'Keamanan Siber', 4),
  ('TECH_CLOUD', 'TECH', 'Cloud & Infrastruktur', 5),
  ('TECH_SUPPORT', 'TECH', 'Dukungan TI', 6),
  ('FIN_BANK', 'FINANCE', 'Bank & Bank Digital', 7),
  ('FIN_PAYMENT', 'FINANCE', 'Payment Gateway', 8),
  ('FIN_LENDING', 'FINANCE', 'Pembiayaan & Lending', 9),
  ('FIN_WEALTH', 'FINANCE', 'WealthTech & Investasi', 10),
  ('INS_AKUNTANSI', 'INSURANCE', 'Akuntansi & Audit', 11),
  ('INS_PAJAK', 'INSURANCE', 'Perpajakan', 12),
  ('INS_ASURANSI', 'INSURANCE', 'Asuransi', 13),
  ('INS_KONSULTAN', 'INSURANCE', 'Konsultan Keuangan', 14),
  ('HLT_RS', 'HEALTH', 'Rumah Sakit', 15),
  ('HLT_KLINIK', 'HEALTH', 'Klinik', 16),
  ('HLT_KECANTIKAN', 'HEALTH', 'Klinik Kecantikan', 17),
  ('HLT_FARMASI_IND', 'HEALTH', 'Industri Farmasi', 18),
  ('HLT_FARMASI_RITEL', 'HEALTH', 'Ritel Farmasi', 19),
  ('HLT_FARMASI_DIST', 'HEALTH', 'Distributor Farmasi', 20),
  ('HLT_FARMASI_STERIL', 'HEALTH', 'Farmasi Steril', 21),
  ('HLT_LAB', 'HEALTH', 'Laboratorium Medis', 22),
  ('HLT_BIOTEK', 'HEALTH', 'Bioteknologi', 23),
  ('HLT_MEDTECH', 'HEALTH', 'MedTech', 24),
  ('HLT_MASYARAKAT', 'HEALTH', 'Kesehatan Masyarakat', 25),
  ('HLT_HEWAN', 'HEALTH', 'Kesehatan Hewan', 26),
  ('EDU_SEKOLAH', 'EDUCATION', 'Sekolah', 27),
  ('EDU_KAMPUS', 'EDUCATION', 'Perguruan Tinggi', 28),
  ('EDU_EDTECH', 'EDUCATION', 'EdTech', 29),
  ('EDU_KURSUS', 'EDUCATION', 'Lembaga Kursus & Pelatihan', 30),
  ('EDU_PUSTAKA', 'EDUCATION', 'Perpustakaan & Arsip', 31),
  ('COM_MARKETPLACE', 'COMMERCE', 'Marketplace', 32),
  ('COM_RITEL', 'COMMERCE', 'Ritel & Barang Konsumsi', 33),
  ('COM_GROSIR', 'COMMERCE', 'Grosir & Distribusi', 34),
  ('COM_D2C', 'COMMERCE', 'Brand D2C', 35),
  ('LOG_GUDANG', 'LOGISTICS', 'Warehouse', 36),
  ('LOG_FREIGHT', 'LOGISTICS', 'Freight Forwarding', 37),
  ('LOG_PELAYARAN', 'LOGISTICS', 'Pelayaran & Kargo', 38),
  ('LOG_LASTMILE', 'LOGISTICS', 'Last Mile & Kurir', 39),
  ('MFG_ELEKTRONIK', 'MANUFACTURING', 'Elektronik', 40),
  ('MFG_OTOMOTIF', 'MANUFACTURING', 'Otomotif', 41),
  ('MFG_TEKSTIL', 'MANUFACTURING', 'Tekstil & Garmen', 42),
  ('MFG_KEMASAN', 'MANUFACTURING', 'Kemasan & Percetakan', 43),
  ('MFG_LOGAM', 'MANUFACTURING', 'Logam & Permesinan', 44),
  ('MFG_KIMIA', 'MANUFACTURING', 'Kimia & Material', 45),
  ('MFG_KAYU', 'MANUFACTURING', 'Kayu & Furnitur', 46),
  ('ENE_MIGAS', 'ENERGY', 'Minyak & Gas', 47),
  ('ENE_TERBARUKAN', 'ENERGY', 'Energi Terbarukan', 48),
  ('ENE_TAMBANG', 'ENERGY', 'Pertambangan', 49),
  ('ENE_LISTRIK', 'ENERGY', 'Ketenagalistrikan', 50),
  ('AGR_PERTANIAN', 'AGRI', 'Pertanian', 51),
  ('AGR_PERKEBUNAN', 'AGRI', 'Perkebunan', 52),
  ('AGR_PERIKANAN', 'AGRI', 'Perikanan & Kelautan', 53),
  ('AGR_PANGAN', 'AGRI', 'Produksi Pangan', 54),
  ('AGR_TERNAK', 'AGRI', 'Peternakan', 55),
  ('CON_PROPERTI', 'CONSTRUCTION', 'Properti & Real Estat', 56),
  ('CON_ARSITEK', 'CONSTRUCTION', 'Arsitektur', 57),
  ('CON_SIPIL', 'CONSTRUCTION', 'Teknik Sipil', 58),
  ('CON_KONTRAKTOR', 'CONSTRUCTION', 'Kontraktor & Instalasi', 59),
  ('TRA_PENERBANGAN', 'TRANSPORT', 'Penerbangan', 60),
  ('TRA_KERETA', 'TRANSPORT', 'Perkeretaapian', 61),
  ('TRA_BENGKEL', 'TRANSPORT', 'Otomotif & Bengkel', 62),
  ('TRA_DARAT', 'TRANSPORT', 'Angkutan Darat', 63),
  ('TEL_ISP', 'TELCO', 'ISP & Jaringan', 64),
  ('TEL_SELULER', 'TELCO', 'Operator Seluler', 65),
  ('TEL_FIBER', 'TELCO', 'Fiber Optik', 66),
  ('TEL_SATELIT', 'TELCO', 'Satelit', 67),
  ('MED_TVRADIO', 'MEDIA', 'Televisi & Radio', 68),
  ('MED_FILM', 'MEDIA', 'Film & Produksi', 69),
  ('MED_MUSIK', 'MEDIA', 'Musik', 70),
  ('MED_STREAMING', 'MEDIA', 'Streaming & Digital', 71),
  ('MED_GAME', 'MEDIA', 'Game', 72),
  ('MED_PERS', 'MEDIA', 'Pers & Jurnalistik', 73),
  ('CRE_UIUX', 'CREATIVE', 'UI/UX', 74),
  ('CRE_GRAFIS', 'CREATIVE', 'Desain Grafis', 75),
  ('CRE_ANIMASI', 'CREATIVE', 'Animasi & VFX', 76),
  ('CRE_PRODUK', 'CREATIVE', 'Desain Produk', 77),
  ('CRE_FOTO', 'CREATIVE', 'Fotografi & Videografi', 78),
  ('CRE_FASHION', 'CREATIVE', 'Fashion & Kriya', 79),
  ('CRE_INTERIOR', 'CREATIVE', 'Desain Interior', 80),
  ('MKT_DIGITAL', 'MARKETING', 'Digital Marketing', 81),
  ('MKT_BRANDING', 'MARKETING', 'Branding', 82),
  ('MKT_PR', 'MARKETING', 'Public Relations', 83),
  ('MKT_AGENCY', 'MARKETING', 'Agency & Periklanan', 84),
  ('LEG_FIRMA', 'LEGAL', 'Firma Hukum', 85),
  ('LEG_COMPLIANCE', 'LEGAL', 'Kepatuhan (Compliance)', 86),
  ('LEG_KEBIJAKAN', 'LEGAL', 'Kebijakan Publik', 87),
  ('GOV_KEMENTERIAN', 'GOVERNMENT', 'Kementerian & Lembaga', 88),
  ('GOV_PEMDA', 'GOVERNMENT', 'Pemerintah Daerah', 89),
  ('GOV_BUMN', 'GOVERNMENT', 'BUMN', 90),
  ('GOV_PENEGAKAN', 'GOVERNMENT', 'Penegakan Hukum', 91),
  ('SUS_ESG', 'SUSTAIN', 'ESG & Keberlanjutan', 92),
  ('SUS_LIMBAH', 'SUSTAIN', 'Pengelolaan Limbah', 93),
  ('SUS_KONSERVASI', 'SUSTAIN', 'Konservasi Lingkungan', 94),
  ('AER_DIRGANTARA', 'AEROSPACE', 'Kedirgantaraan', 95),
  ('AER_DRONE', 'AEROSPACE', 'Drone & UAV', 96),
  ('DEF_MILITER', 'DEFENSE', 'Pertahanan & Militer', 97),
  ('DEF_KEAMANAN', 'DEFENSE', 'Jasa Keamanan', 98),
  ('NGO_LEMBAGA', 'NGO', 'Lembaga Sosial', 99),
  ('NGO_KEMANUSIAAN', 'NGO', 'Kemanusiaan', 100),
  ('NGO_MASYARAKAT', 'NGO', 'Pengembangan Masyarakat', 101),
  ('HOS_HOTEL', 'HOSPITALITY', 'Hotel & Resort', 102),
  ('HOS_TRAVEL', 'HOSPITALITY', 'Travel & Wisata', 103),
  ('HOS_EVENT', 'HOSPITALITY', 'Event Organizer', 104),
  ('FNB_RESTORAN', 'FNB', 'Restoran & Kafe', 105),
  ('FNB_KATERING', 'FNB', 'Katering', 106),
  ('FNB_LAYANAN', 'FNB', 'Layanan Pangan', 107),
  ('RES_LEMBAGA', 'RESEARCH', 'Lembaga Riset', 108),
  ('RES_LAB', 'RESEARCH', 'Laboratorium Uji', 109),
  ('RES_ILMIAH', 'RESEARCH', 'Jasa Ilmiah', 110)
on conflict (code) do update set
  industry_code = excluded.industry_code, name_id = excluded.name_id,
  display_order = excluded.display_order;

insert into public.career_sub_industries (career_id, sub_industry_code, is_primary, display_order, source) values
  (1, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (2, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (3, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (4, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (5, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (6, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (7, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (8, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (8, 'TECH_SOFTWARE', false, 2, 'aturan_kata_kunci'),
  (9, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (9, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (10, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (11, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (11, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (12, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (12, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (13, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (13, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (14, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (14, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (15, 'TECH_CLOUD', true, 1, 'aturan_kata_kunci'),
  (15, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (16, 'TECH_CLOUD', true, 1, 'aturan_kata_kunci'),
  (16, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (17, 'TECH_CLOUD', true, 1, 'aturan_kata_kunci'),
  (17, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (18, 'TECH_CYBER', true, 1, 'aturan_kata_kunci'),
  (18, 'DEF_KEAMANAN', false, 2, 'aturan_kata_kunci'),
  (19, 'TECH_CYBER', true, 1, 'aturan_kata_kunci'),
  (19, 'TECH_SAAS', false, 2, 'aturan_kata_kunci'),
  (20, 'CRE_UIUX', true, 1, 'aturan_kata_kunci'),
  (21, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (22, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (22, 'TECH_SOFTWARE', false, 2, 'aturan_kata_kunci'),
  (22, 'MFG_ELEKTRONIK', false, 3, 'aturan_kata_kunci'),
  (23, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (24, 'TECH_SUPPORT', true, 1, 'aturan_kata_kunci'),
  (25, 'TECH_SUPPORT', true, 1, 'aturan_kata_kunci'),
  (26, 'TEL_ISP', true, 1, 'aturan_kata_kunci'),
  (26, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (27, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (28, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (29, 'MKT_DIGITAL', true, 1, 'aturan_kata_kunci'),
  (30, 'TECH_SOFTWARE', true, 1, 'aturan_kata_kunci'),
  (30, 'MED_GAME', false, 2, 'aturan_kata_kunci'),
  (31, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (32, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (32, 'TECH_SOFTWARE', false, 2, 'aturan_kata_kunci'),
  (33, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (34, 'MFG_ELEKTRONIK', true, 1, 'aturan_kata_kunci'),
  (34, 'TECH_CLOUD', false, 2, 'aturan_kata_kunci'),
  (35, 'MED_PERS', true, 1, 'aturan_kata_kunci'),
  (36, 'MKT_BRANDING', true, 1, 'aturan_kata_kunci'),
  (37, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (38, 'MKT_PR', true, 1, 'aturan_kata_kunci'),
  (39, 'GOV_BUMN', true, 1, 'rumpun_soc'),
  (40, 'INS_AKUNTANSI', true, 1, 'aturan_kata_kunci'),
  (40, 'FIN_WEALTH', false, 2, 'aturan_kata_kunci'),
  (41, 'FIN_WEALTH', true, 1, 'aturan_kata_kunci'),
  (42, 'GOV_BUMN', true, 1, 'rumpun_soc'),
  (43, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (48, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (49, 'LOG_FREIGHT', true, 1, 'aturan_kata_kunci'),
  (51, 'LEG_COMPLIANCE', true, 1, 'aturan_kata_kunci'),
  (52, 'LEG_COMPLIANCE', true, 1, 'aturan_kata_kunci'),
  (53, 'DEF_KEAMANAN', true, 1, 'aturan_kata_kunci'),
  (53, 'HOS_EVENT', false, 2, 'aturan_kata_kunci'),
  (57, 'MKT_AGENCY', true, 1, 'aturan_kata_kunci'),
  (58, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (58, 'AGR_PERTANIAN', false, 2, 'aturan_kata_kunci'),
  (59, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (60, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (61, 'INS_ASURANSI', true, 1, 'aturan_kata_kunci'),
  (62, 'LEG_COMPLIANCE', true, 1, 'aturan_kata_kunci'),
  (66, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (66, 'LEG_COMPLIANCE', false, 2, 'aturan_kata_kunci'),
  (68, 'LOG_FREIGHT', true, 1, 'aturan_kata_kunci'),
  (69, 'LOG_FREIGHT', true, 1, 'aturan_kata_kunci'),
  (69, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (69, 'RES_ILMIAH', false, 3, 'aturan_kata_kunci'),
  (70, 'LOG_FREIGHT', true, 1, 'aturan_kata_kunci'),
  (70, 'RES_ILMIAH', false, 2, 'aturan_kata_kunci'),
  (71, 'MKT_BRANDING', true, 1, 'aturan_kata_kunci'),
  (72, 'INS_AKUNTANSI', true, 1, 'aturan_kata_kunci'),
  (73, 'INS_KONSULTAN', true, 1, 'aturan_kata_kunci'),
  (73, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (74, 'INS_KONSULTAN', true, 1, 'aturan_kata_kunci'),
  (74, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (75, 'INS_AKUNTANSI', true, 1, 'aturan_kata_kunci'),
  (76, 'FIN_BANK', true, 1, 'aturan_kata_kunci'),
  (77, 'FIN_WEALTH', true, 1, 'aturan_kata_kunci'),
  (78, 'INS_KONSULTAN', true, 1, 'rumpun_soc'),
  (79, 'INS_ASURANSI', true, 1, 'aturan_kata_kunci'),
  (80, 'FIN_LENDING', true, 1, 'aturan_kata_kunci'),
  (81, 'FIN_BANK', true, 1, 'aturan_kata_kunci'),
  (82, 'INS_KONSULTAN', true, 1, 'aturan_kata_kunci'),
  (82, 'NGO_LEMBAGA', false, 2, 'aturan_kata_kunci'),
  (83, 'FIN_BANK', true, 1, 'aturan_kata_kunci'),
  (84, 'INS_PAJAK', true, 1, 'aturan_kata_kunci'),
  (87, 'FIN_WEALTH', true, 1, 'aturan_kata_kunci'),
  (88, 'FIN_LENDING', true, 1, 'aturan_kata_kunci'),
  (89, 'HLT_MASYARAKAT', true, 1, 'aturan_kata_kunci'),
  (90, 'TECH_SUPPORT', true, 1, 'aturan_kata_kunci'),
  (91, 'TEL_ISP', true, 1, 'aturan_kata_kunci'),
  (91, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (92, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (93, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (95, 'TECH_SOFTWARE', true, 1, 'rumpun_soc'),
  (96, 'RES_ILMIAH', true, 1, 'aturan_kata_kunci'),
  (97, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (98, 'DEF_KEAMANAN', true, 1, 'aturan_kata_kunci'),
  (98, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (99, 'TECH_CYBER', true, 1, 'aturan_kata_kunci'),
  (100, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (101, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (102, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (102, 'RES_LEMBAGA', false, 2, 'aturan_kata_kunci'),
  (103, 'TECH_AI', true, 1, 'aturan_kata_kunci'),
  (104, 'HLT_BIOTEK', true, 1, 'aturan_kata_kunci'),
  (104, 'TECH_AI', false, 2, 'aturan_kata_kunci'),
  (105, 'TECH_SAAS', true, 1, 'aturan_kata_kunci'),
  (106, 'MFG_ELEKTRONIK', true, 1, 'aturan_kata_kunci'),
  (106, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (107, 'MFG_ELEKTRONIK', true, 1, 'aturan_kata_kunci'),
  (107, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (108, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (109, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (110, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (111, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (112, 'LOG_PELAYARAN', true, 1, 'aturan_kata_kunci'),
  (112, 'CON_ARSITEK', false, 2, 'aturan_kata_kunci'),
  (112, 'MFG_ELEKTRONIK', false, 3, 'aturan_kata_kunci'),
  (113, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (114, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (116, 'MFG_OTOMOTIF', true, 1, 'aturan_kata_kunci'),
  (116, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (117, 'ENE_TAMBANG', true, 1, 'aturan_kata_kunci'),
  (117, 'RES_LEMBAGA', false, 2, 'aturan_kata_kunci'),
  (117, 'MFG_ELEKTRONIK', false, 3, 'aturan_kata_kunci'),
  (118, 'ENE_LISTRIK', true, 1, 'aturan_kata_kunci'),
  (118, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (119, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (119, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (121, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (122, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (125, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (127, 'ENE_TERBARUKAN', true, 1, 'aturan_kata_kunci'),
  (127, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (128, 'ENE_TERBARUKAN', true, 1, 'aturan_kata_kunci'),
  (128, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (129, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (130, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (131, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (132, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (133, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (133, 'RES_ILMIAH', false, 2, 'aturan_kata_kunci'),
  (134, 'RES_LEMBAGA', true, 1, 'rumpun_soc'),
  (135, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (136, 'RES_LEMBAGA', true, 1, 'rumpun_soc'),
  (139, 'RES_LAB', true, 1, 'aturan_kata_kunci'),
  (140, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (141, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (142, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (143, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (143, 'CON_ARSITEK', false, 2, 'aturan_kata_kunci'),
  (144, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (145, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (145, 'AGR_PERTANIAN', false, 2, 'aturan_kata_kunci'),
  (146, 'HLT_BIOTEK', true, 1, 'aturan_kata_kunci'),
  (146, 'EDU_KAMPUS', false, 2, 'aturan_kata_kunci'),
  (147, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (147, 'SUS_KONSERVASI', false, 2, 'aturan_kata_kunci'),
  (148, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (148, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (149, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (149, 'MFG_KIMIA', false, 2, 'aturan_kata_kunci'),
  (150, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (150, 'SUS_ESG', false, 2, 'aturan_kata_kunci'),
  (151, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (152, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (153, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (154, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (155, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (156, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (157, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (158, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (160, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (161, 'HLT_RS', true, 1, 'aturan_kata_kunci'),
  (161, 'EDU_KAMPUS', false, 2, 'aturan_kata_kunci'),
  (162, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (162, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (163, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (164, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (164, 'LEG_FIRMA', false, 2, 'aturan_kata_kunci'),
  (164, 'GOV_PENEGAKAN', false, 3, 'aturan_kata_kunci'),
  (165, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (165, 'LEG_FIRMA', false, 2, 'aturan_kata_kunci'),
  (166, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (166, 'NGO_LEMBAGA', false, 2, 'aturan_kata_kunci'),
  (167, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (168, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (169, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (169, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (170, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (171, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (172, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (173, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (174, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (175, 'EDU_KURSUS', true, 1, 'aturan_kata_kunci'),
  (175, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (175, 'TRA_DARAT', false, 3, 'aturan_kata_kunci'),
  (177, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (178, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (179, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (180, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (181, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (182, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (183, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (184, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (184, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (185, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (185, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (186, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (186, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (187, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (187, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (188, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (188, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (190, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (190, 'AGR_PERIKANAN', false, 2, 'aturan_kata_kunci'),
  (191, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (191, 'EDU_KURSUS', false, 2, 'aturan_kata_kunci'),
  (191, 'AGR_PERIKANAN', false, 3, 'aturan_kata_kunci'),
  (192, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (192, 'EDU_KURSUS', false, 2, 'aturan_kata_kunci'),
  (193, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (193, 'EDU_KURSUS', false, 2, 'aturan_kata_kunci'),
  (194, 'EDU_SEKOLAH', true, 1, 'aturan_kata_kunci'),
  (194, 'EDU_KURSUS', false, 2, 'aturan_kata_kunci'),
  (196, 'EDU_PUSTAKA', true, 1, 'aturan_kata_kunci'),
  (197, 'EDU_PUSTAKA', true, 1, 'aturan_kata_kunci'),
  (198, 'EDU_PUSTAKA', true, 1, 'aturan_kata_kunci'),
  (199, 'EDU_PUSTAKA', true, 1, 'aturan_kata_kunci'),
  (200, 'EDU_PUSTAKA', true, 1, 'aturan_kata_kunci'),
  (201, 'AGR_PERTANIAN', true, 1, 'aturan_kata_kunci'),
  (202, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (203, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (204, 'EDU_SEKOLAH', true, 1, 'rumpun_soc'),
  (205, 'EDU_KAMPUS', true, 1, 'aturan_kata_kunci'),
  (208, 'CRE_GRAFIS', true, 1, 'rumpun_soc'),
  (209, 'CRE_FASHION', true, 1, 'aturan_kata_kunci'),
  (210, 'CRE_GRAFIS', true, 1, 'rumpun_soc'),
  (211, 'CRE_ANIMASI', true, 1, 'aturan_kata_kunci'),
  (213, 'CRE_PRODUK', true, 1, 'aturan_kata_kunci'),
  (214, 'CRE_FASHION', true, 1, 'aturan_kata_kunci'),
  (215, 'CRE_FASHION', true, 1, 'aturan_kata_kunci'),
  (216, 'CRE_GRAFIS', true, 1, 'rumpun_soc'),
  (217, 'CRE_INTERIOR', true, 1, 'aturan_kata_kunci'),
  (218, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (219, 'CRE_PRODUK', true, 1, 'aturan_kata_kunci'),
  (221, 'MED_FILM', true, 1, 'aturan_kata_kunci'),
  (222, 'MED_TVRADIO', true, 1, 'aturan_kata_kunci'),
  (223, 'MED_FILM', true, 1, 'aturan_kata_kunci'),
  (224, 'MED_TVRADIO', true, 1, 'aturan_kata_kunci'),
  (225, 'MED_MUSIK', true, 1, 'aturan_kata_kunci'),
  (225, 'LOG_LASTMILE', false, 2, 'aturan_kata_kunci'),
  (226, 'MED_TVRADIO', true, 1, 'aturan_kata_kunci'),
  (227, 'MED_PERS', true, 1, 'aturan_kata_kunci'),
  (228, 'MKT_PR', true, 1, 'aturan_kata_kunci'),
  (229, 'MED_PERS', true, 1, 'aturan_kata_kunci'),
  (230, 'MED_PERS', true, 1, 'aturan_kata_kunci'),
  (231, 'MED_PERS', true, 1, 'aturan_kata_kunci'),
  (232, 'MED_PERS', true, 1, 'aturan_kata_kunci'),
  (235, 'CRE_FOTO', true, 1, 'aturan_kata_kunci'),
  (236, 'CRE_FOTO', true, 1, 'aturan_kata_kunci'),
  (236, 'MED_TVRADIO', false, 2, 'aturan_kata_kunci'),
  (237, 'CRE_FOTO', true, 1, 'aturan_kata_kunci'),
  (237, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (238, 'CRE_FOTO', true, 1, 'aturan_kata_kunci'),
  (239, 'CRE_FOTO', true, 1, 'aturan_kata_kunci'),
  (240, 'CRE_FOTO', true, 1, 'aturan_kata_kunci'),
  (241, 'CRE_FOTO', true, 1, 'aturan_kata_kunci'),
  (241, 'MED_PERS', false, 2, 'aturan_kata_kunci'),
  (243, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (244, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (244, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (245, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (245, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (246, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (246, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (247, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (247, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (249, 'HLT_RS', true, 1, 'rumpun_soc'),
  (250, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (251, 'HLT_FARMASI_RITEL', true, 1, 'aturan_kata_kunci'),
  (251, 'HLT_FARMASI_IND', false, 2, 'aturan_kata_kunci'),
  (255, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (257, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (258, 'HLT_MEDTECH', true, 1, 'aturan_kata_kunci'),
  (260, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (261, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (262, 'HLT_RS', true, 1, 'rumpun_soc'),
  (264, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (265, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (265, 'MED_MUSIK', false, 2, 'aturan_kata_kunci'),
  (266, 'HLT_HEWAN', true, 1, 'aturan_kata_kunci'),
  (266, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (267, 'HLT_RS', true, 1, 'rumpun_soc'),
  (268, 'HLT_RS', true, 1, 'rumpun_soc'),
  (269, 'HLT_RS', true, 1, 'rumpun_soc'),
  (270, 'HLT_RS', true, 1, 'rumpun_soc'),
  (271, 'HLT_RS', true, 1, 'rumpun_soc'),
  (272, 'HLT_RS', true, 1, 'rumpun_soc'),
  (273, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (273, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (275, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (276, 'HLT_RS', true, 1, 'rumpun_soc'),
  (277, 'HLT_RS', true, 1, 'rumpun_soc'),
  (278, 'HLT_RS', true, 1, 'rumpun_soc'),
  (279, 'HLT_RS', true, 1, 'rumpun_soc'),
  (280, 'HLT_RS', true, 1, 'rumpun_soc'),
  (281, 'HLT_RS', true, 1, 'rumpun_soc'),
  (282, 'HLT_RS', true, 1, 'rumpun_soc'),
  (283, 'HLT_RS', true, 1, 'rumpun_soc'),
  (284, 'HLT_RS', true, 1, 'rumpun_soc'),
  (285, 'HLT_LAB', true, 1, 'aturan_kata_kunci'),
  (285, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (286, 'HLT_RS', true, 1, 'rumpun_soc'),
  (287, 'HLT_RS', true, 1, 'rumpun_soc'),
  (289, 'HLT_RS', true, 1, 'rumpun_soc'),
  (291, 'HLT_RS', true, 1, 'rumpun_soc'),
  (292, 'HLT_RS', true, 1, 'rumpun_soc'),
  (293, 'HLT_RS', true, 1, 'aturan_kata_kunci'),
  (293, 'NGO_MASYARAKAT', false, 2, 'aturan_kata_kunci'),
  (294, 'HLT_RS', true, 1, 'rumpun_soc'),
  (295, 'HLT_RS', true, 1, 'rumpun_soc'),
  (296, 'HLT_RS', true, 1, 'rumpun_soc'),
  (297, 'HLT_RS', true, 1, 'rumpun_soc'),
  (299, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (300, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (304, 'HLT_LAB', true, 1, 'aturan_kata_kunci'),
  (304, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (305, 'HLT_BIOTEK', true, 1, 'aturan_kata_kunci'),
  (306, 'HLT_LAB', true, 1, 'aturan_kata_kunci'),
  (306, 'RES_ILMIAH', false, 2, 'aturan_kata_kunci'),
  (307, 'HLT_LAB', true, 1, 'aturan_kata_kunci'),
  (307, 'RES_ILMIAH', false, 2, 'aturan_kata_kunci'),
  (308, 'HLT_LAB', true, 1, 'aturan_kata_kunci'),
  (308, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (309, 'HLT_RS', true, 1, 'rumpun_soc'),
  (310, 'HLT_RS', true, 1, 'rumpun_soc'),
  (311, 'HLT_RS', true, 1, 'rumpun_soc'),
  (312, 'HLT_MEDTECH', true, 1, 'aturan_kata_kunci'),
  (312, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (312, 'ENE_LISTRIK', false, 3, 'aturan_kata_kunci'),
  (313, 'HLT_MEDTECH', true, 1, 'aturan_kata_kunci'),
  (314, 'HLT_MEDTECH', true, 1, 'aturan_kata_kunci'),
  (315, 'HLT_MEDTECH', true, 1, 'aturan_kata_kunci'),
  (315, 'RES_LEMBAGA', false, 2, 'aturan_kata_kunci'),
  (316, 'HLT_RS', true, 1, 'rumpun_soc'),
  (317, 'HLT_RS', true, 1, 'rumpun_soc'),
  (318, 'HLT_RS', true, 1, 'rumpun_soc'),
  (319, 'HLT_FARMASI_IND', true, 1, 'aturan_kata_kunci'),
  (321, 'HLT_MEDTECH', true, 1, 'aturan_kata_kunci'),
  (321, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (322, 'HLT_HEWAN', true, 1, 'aturan_kata_kunci'),
  (322, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (323, 'HLT_RS', true, 1, 'rumpun_soc'),
  (324, 'HLT_RS', true, 1, 'rumpun_soc'),
  (325, 'HLT_RS', true, 1, 'aturan_kata_kunci'),
  (325, 'HLT_MASYARAKAT', false, 2, 'aturan_kata_kunci'),
  (326, 'HLT_RS', true, 1, 'rumpun_soc'),
  (327, 'HLT_MEDTECH', true, 1, 'aturan_kata_kunci'),
  (328, 'HLT_RS', true, 1, 'rumpun_soc'),
  (330, 'HLT_RS', true, 1, 'rumpun_soc'),
  (331, 'HLT_RS', true, 1, 'rumpun_soc'),
  (332, 'HLT_RS', true, 1, 'rumpun_soc'),
  (333, 'HLT_MASYARAKAT', true, 1, 'aturan_kata_kunci'),
  (334, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (335, 'HLT_BIOTEK', true, 1, 'aturan_kata_kunci'),
  (335, 'NGO_LEMBAGA', false, 2, 'aturan_kata_kunci'),
  (336, 'HLT_RS', true, 1, 'rumpun_soc'),
  (338, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (339, 'HLT_RS', true, 1, 'rumpun_soc'),
  (340, 'HLT_RS', true, 1, 'rumpun_soc'),
  (341, 'HLT_RS', true, 1, 'rumpun_soc'),
  (342, 'HLT_RS', true, 1, 'rumpun_soc'),
  (343, 'HLT_RS', true, 1, 'rumpun_soc'),
  (346, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (348, 'HLT_KECANTIKAN', true, 1, 'aturan_kata_kunci'),
  (348, 'HLT_KLINIK', false, 2, 'aturan_kata_kunci'),
  (349, 'HLT_KLINIK', true, 1, 'aturan_kata_kunci'),
  (349, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (351, 'HLT_FARMASI_STERIL', true, 1, 'aturan_kata_kunci'),
  (351, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (353, 'HLT_FARMASI_RITEL', true, 1, 'aturan_kata_kunci'),
  (354, 'HLT_HEWAN', true, 1, 'aturan_kata_kunci'),
  (354, 'HLT_RS', false, 2, 'aturan_kata_kunci'),
  (355, 'HLT_LAB', true, 1, 'aturan_kata_kunci'),
  (358, 'HLT_RS', true, 1, 'rumpun_soc'),
  (360, 'HLT_KECANTIKAN', true, 1, 'aturan_kata_kunci'),
  (361, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (362, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (363, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (365, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (366, 'HLT_KECANTIKAN', true, 1, 'aturan_kata_kunci'),
  (366, 'COM_RITEL', false, 2, 'aturan_kata_kunci'),
  (367, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (368, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (369, 'INS_ASURANSI', true, 1, 'aturan_kata_kunci'),
  (370, 'FIN_WEALTH', true, 1, 'aturan_kata_kunci'),
  (370, 'COM_RITEL', false, 2, 'aturan_kata_kunci'),
  (371, 'HOS_TRAVEL', true, 1, 'aturan_kata_kunci'),
  (373, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (374, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (375, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (376, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (377, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (378, 'CON_PROPERTI', true, 1, 'aturan_kata_kunci'),
  (378, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (379, 'CON_KONTRAKTOR', true, 1, 'aturan_kata_kunci'),
  (380, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (380, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (381, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (382, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (384, 'FIN_BANK', true, 1, 'aturan_kata_kunci'),
  (386, 'FIN_BANK', true, 1, 'aturan_kata_kunci'),
  (387, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (388, 'FIN_BANK', true, 1, 'aturan_kata_kunci'),
  (389, 'COM_RITEL', true, 1, 'rumpun_soc'),
  (390, 'LOG_FREIGHT', true, 1, 'aturan_kata_kunci'),
  (391, 'LOG_FREIGHT', true, 1, 'aturan_kata_kunci'),
  (392, 'LOG_LASTMILE', true, 1, 'aturan_kata_kunci'),
  (393, 'HLT_KECANTIKAN', true, 1, 'aturan_kata_kunci'),
  (393, 'LOG_LASTMILE', false, 2, 'aturan_kata_kunci'),
  (394, 'LOG_LASTMILE', true, 1, 'aturan_kata_kunci'),
  (395, 'LOG_LASTMILE', true, 1, 'aturan_kata_kunci'),
  (396, 'LOG_LASTMILE', true, 1, 'aturan_kata_kunci'),
  (397, 'LOG_LASTMILE', true, 1, 'aturan_kata_kunci'),
  (398, 'LOG_GUDANG', true, 1, 'aturan_kata_kunci'),
  (399, 'LOG_GUDANG', true, 1, 'aturan_kata_kunci'),
  (400, 'LOG_GUDANG', true, 1, 'aturan_kata_kunci'),
  (401, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (401, 'ENE_TERBARUKAN', false, 2, 'aturan_kata_kunci'),
  (401, 'CON_KONTRAKTOR', false, 3, 'aturan_kata_kunci'),
  (402, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (402, 'ENE_TERBARUKAN', false, 2, 'aturan_kata_kunci'),
  (402, 'CON_KONTRAKTOR', false, 3, 'aturan_kata_kunci'),
  (403, 'ENE_TERBARUKAN', true, 1, 'aturan_kata_kunci'),
  (403, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (404, 'INS_AKUNTANSI', true, 1, 'aturan_kata_kunci'),
  (404, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (405, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (406, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (407, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (408, 'ENE_TAMBANG', true, 1, 'aturan_kata_kunci'),
  (409, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (409, 'ENE_MIGAS', false, 2, 'aturan_kata_kunci'),
  (410, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (410, 'ENE_TAMBANG', false, 2, 'aturan_kata_kunci'),
  (411, 'ENE_TAMBANG', true, 1, 'aturan_kata_kunci'),
  (412, 'ENE_TAMBANG', true, 1, 'aturan_kata_kunci'),
  (413, 'HLT_KECANTIKAN', true, 1, 'aturan_kata_kunci'),
  (413, 'ENE_TAMBANG', false, 2, 'aturan_kata_kunci'),
  (415, 'ENE_TAMBANG', true, 1, 'aturan_kata_kunci'),
  (416, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (417, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (417, 'ENE_TAMBANG', false, 2, 'aturan_kata_kunci'),
  (419, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (420, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (420, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (421, 'HLT_RS', true, 1, 'aturan_kata_kunci'),
  (421, 'TRA_PENERBANGAN', false, 2, 'aturan_kata_kunci'),
  (422, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (423, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (423, 'TRA_BENGKEL', false, 2, 'aturan_kata_kunci'),
  (424, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (425, 'TRA_BENGKEL', true, 1, 'aturan_kata_kunci'),
  (425, 'TRA_DARAT', false, 2, 'aturan_kata_kunci'),
  (426, 'AGR_PERTANIAN', true, 1, 'aturan_kata_kunci'),
  (426, 'TRA_BENGKEL', false, 2, 'aturan_kata_kunci'),
  (427, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (428, 'HLT_RS', true, 1, 'aturan_kata_kunci'),
  (428, 'TRA_KERETA', false, 2, 'aturan_kata_kunci'),
  (429, 'LOG_PELAYARAN', true, 1, 'aturan_kata_kunci'),
  (429, 'TRA_BENGKEL', false, 2, 'aturan_kata_kunci'),
  (430, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (431, 'MFG_KAYU', true, 1, 'aturan_kata_kunci'),
  (431, 'TRA_BENGKEL', false, 2, 'aturan_kata_kunci'),
  (432, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (434, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (435, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (435, 'CON_KONTRAKTOR', false, 2, 'aturan_kata_kunci'),
  (436, 'TRA_BENGKEL', true, 1, 'rumpun_soc'),
  (437, 'ENE_TERBARUKAN', true, 1, 'aturan_kata_kunci'),
  (438, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (439, 'MFG_ELEKTRONIK', true, 1, 'aturan_kata_kunci'),
  (439, 'AER_DIRGANTARA', false, 2, 'aturan_kata_kunci'),
  (439, 'TRA_PENERBANGAN', false, 3, 'aturan_kata_kunci'),
  (440, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (441, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (442, 'MFG_ELEKTRONIK', true, 1, 'aturan_kata_kunci'),
  (442, 'TRA_BENGKEL', false, 2, 'aturan_kata_kunci'),
  (443, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (444, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (445, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (445, 'MFG_ELEKTRONIK', false, 2, 'aturan_kata_kunci'),
  (447, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (449, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (450, 'AGR_TERNAK', true, 1, 'aturan_kata_kunci'),
  (451, 'AGR_PERIKANAN', true, 1, 'aturan_kata_kunci'),
  (451, 'AGR_TERNAK', false, 2, 'aturan_kata_kunci'),
  (452, 'AGR_TERNAK', true, 1, 'aturan_kata_kunci'),
  (453, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (454, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (455, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (457, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (458, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (459, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (460, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (461, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (462, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (463, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (464, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (465, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (466, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (467, 'MED_FILM', true, 1, 'aturan_kata_kunci'),
  (467, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (468, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (468, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (469, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (469, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (469, 'MFG_TEKSTIL', false, 3, 'aturan_kata_kunci'),
  (470, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (471, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (472, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (473, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (473, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (474, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (475, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (476, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (477, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (478, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (478, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (479, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (481, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (481, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (482, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (483, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (484, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (485, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (485, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (486, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (487, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (488, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (489, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (490, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (491, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (492, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (493, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (494, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (495, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (496, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (497, 'MFG_TEKSTIL', true, 1, 'aturan_kata_kunci'),
  (499, 'MFG_KAYU', true, 1, 'aturan_kata_kunci'),
  (500, 'MFG_KAYU', true, 1, 'aturan_kata_kunci'),
  (503, 'MFG_KAYU', true, 1, 'aturan_kata_kunci'),
  (504, 'MFG_KAYU', true, 1, 'aturan_kata_kunci'),
  (507, 'HLT_KECANTIKAN', true, 1, 'aturan_kata_kunci'),
  (507, 'LOG_LASTMILE', false, 2, 'aturan_kata_kunci'),
  (507, 'ENE_LISTRIK', false, 3, 'aturan_kata_kunci'),
  (508, 'ENE_LISTRIK', true, 1, 'aturan_kata_kunci'),
  (509, 'ENE_TERBARUKAN', true, 1, 'aturan_kata_kunci'),
  (509, 'ENE_LISTRIK', false, 2, 'aturan_kata_kunci'),
  (510, 'ENE_TERBARUKAN', true, 1, 'aturan_kata_kunci'),
  (510, 'ENE_LISTRIK', false, 2, 'aturan_kata_kunci'),
  (511, 'ENE_LISTRIK', true, 1, 'aturan_kata_kunci'),
  (512, 'SUS_LIMBAH', true, 1, 'aturan_kata_kunci'),
  (513, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (514, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (515, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (517, 'ENE_TERBARUKAN', true, 1, 'aturan_kata_kunci'),
  (518, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (519, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (520, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (522, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (524, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (525, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (526, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (527, 'LOG_LASTMILE', true, 1, 'aturan_kata_kunci'),
  (527, 'MFG_KIMIA', false, 2, 'aturan_kata_kunci'),
  (533, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (538, 'MFG_LOGAM', true, 1, 'aturan_kata_kunci'),
  (539, 'TECH_SOFTWARE', true, 1, 'aturan_kata_kunci'),
  (539, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (540, 'MFG_KIMIA', true, 1, 'aturan_kata_kunci'),
  (541, 'HLT_FARMASI_STERIL', true, 1, 'aturan_kata_kunci'),
  (541, 'TRA_DARAT', false, 2, 'aturan_kata_kunci'),
  (542, 'AGR_PANGAN', true, 1, 'aturan_kata_kunci'),
  (544, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (544, 'MFG_LOGAM', false, 2, 'aturan_kata_kunci'),
  (546, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (546, 'MFG_KIMIA', false, 2, 'aturan_kata_kunci'),
  (548, 'MFG_KEMASAN', true, 1, 'aturan_kata_kunci'),
  (550, 'MFG_ELEKTRONIK', true, 1, 'rumpun_soc'),
  (552, 'COM_RITEL', true, 1, 'aturan_kata_kunci'),
  (553, 'TRA_DARAT', true, 1, 'aturan_kata_kunci'),
  (553, 'COM_RITEL', false, 2, 'aturan_kata_kunci'),
  (554, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (555, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (556, 'LOG_PELAYARAN', true, 1, 'aturan_kata_kunci'),
  (557, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (558, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (559, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (560, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (561, 'SUS_LIMBAH', true, 1, 'aturan_kata_kunci'),
  (562, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (563, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (564, 'LOG_GUDANG', true, 1, 'aturan_kata_kunci'),
  (565, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (566, 'TRA_DARAT', true, 1, 'rumpun_soc'),
  (567, 'ENE_MIGAS', true, 1, 'aturan_kata_kunci'),
  (567, 'TRA_DARAT', false, 2, 'aturan_kata_kunci'),
  (568, 'SUS_LIMBAH', true, 1, 'aturan_kata_kunci')
on conflict (career_id, sub_industry_code) do update set
  is_primary = excluded.is_primary, display_order = excluded.display_order,
  source = excluded.source;

-- ---------------------------------------------------------------------------
-- Menutup lubang 0010: profesi yang sub-industrinya bernaung di industri baru
-- kini punya tautan industri juga. Ditandai 'turunan_subindustri' supaya bisa
-- dibedakan dari 636 tautan hasil kurasi manual di 0003.
-- ---------------------------------------------------------------------------
insert into public.career_industries (career_id, industry_code, source, is_verified)
select distinct csi.career_id, si.industry_code, 'turunan_subindustri', false
from public.career_sub_industries csi
join public.sub_industries si on si.code = csi.sub_industry_code
on conflict (career_id, industry_code) do nothing;

do $$
declare n int;
begin
  select count(*) into n from public.careers c
  where c.is_active and not exists (
    select 1 from public.career_sub_industries x where x.career_id = c.id and x.is_primary);
  if n > 0 then raise exception '% profesi aktif tidak punya sub-industri utama', n; end if;

  select count(*) into n from public.industries i
  where i.is_active and not exists (select 1 from public.sub_industries s where s.industry_code = i.code);
  if n > 0 then raise exception '% industri aktif tidak punya sub-industri', n; end if;
end $$;

alter table public.sub_industries        enable row level security;
alter table public.career_sub_industries enable row level security;
do $$
declare t text;
begin
  foreach t in array array['sub_industries','career_sub_industries'] loop
    execute format('drop policy if exists %I_read_all on public.%I', t, t);
    execute format('create policy %I_read_all on public.%I for select to anon, authenticated using (true)', t, t);
  end loop;
end $$;

commit;
